# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sport_development

test:
  <<: *default
  database: sport_test

production:
  primary:
    <<: *default
    database: sport_production
  cache:
    <<: *default
    database: sport_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: sport_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: sport_production_cable
    migrations_paths: db/cable_migrate
